services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=uploads
      # Add your OpenAI API key as environment variable or in .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      # Mount backend directory for development (uncomment for development)
      # - ./backend:/app
      # - /app/node_modules
      # Persistent uploads directory
      - uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads: