import { AIService, AnalysisResult } from './types';

export class MockNotionAIService implements AIService {
  name = 'Notion AI (Mock)';

  isAvailable(): boolean {
    return true; // Always available for demo
  }

  async analyze(resumeContent: string, jobDescription: string): Promise<AnalysisResult> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));

    // Generate mock analysis based on content length and keywords
    const resumeWords = resumeContent.split(' ').length;
    const jobWords = jobDescription.split(' ').length;
    
    return {
      summary: `Notion AI has analyzed your ${resumeWords}-word resume against this ${jobWords}-word job description. The analysis shows a moderate to strong alignment with several opportunities for optimization.`,
      strengths: [
        'Strong professional experience demonstrated',
        'Good educational background alignment',
        'Clear career progression shown',
        'Relevant technical skills mentioned'
      ],
      improvements: [
        'Add more quantified achievements',
        'Include industry-specific keywords',
        'Strengthen the summary section',
        'Better highlight leadership experience'
      ],
      keywordMatch: Math.floor(60 + Math.random() * 25), // 60-85%
      skillGaps: [
        'Machine Learning frameworks',
        'Project management certification',
        'Cloud computing experience',
        'Data analysis tools'
      ],
      recommendations: [
        'Restructure experience section for better flow',
        'Add specific metrics to achievements',
        'Include relevant certifications',
        'Tailor keywords to match job requirements',
        'Strengthen technical skills section'
      ],
      optimizedContent: `MOCK OPTIMIZED CONTENT:\n\n• Led cross-functional team of 8 developers to deliver enterprise software solution, resulting in 40% improvement in processing efficiency\n• Implemented automated testing protocols that reduced deployment time by 60% and improved code quality metrics\n• Collaborated with stakeholders to gather requirements and translate business needs into technical specifications\n\n(This is mock content generated by Notion AI simulation)`
    };
  }
}